# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Build and Publish

on: push

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2.11.1
      with:
        gradle-version: current
        arguments: build
    - uses: actions/upload-artifact@v3
      with:
        name: Artifacts
        path: build/libs
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        name: Test Release
        draft: true
        files: |
          build/libs/GameBridge-0.1.1.jar
          build/libs/GameBridge-0.1.1-sources.jar
      
