# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Compiling and publishing

on:
  push:
    branches: [ "*.*.*" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Extract branch name
      shell: bash
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      id: extract_branch
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Build Jar Files
      uses: gradle/gradle-build-action@v2.11.1
      with:
        gradle-version: current
        arguments: build
        
    - name: Upload Jars as Release Tag
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: ${{ steps.extract_branch.outputs.branch }}
        tag_name: ${{ steps.extract_branch.outputs.branch }}
        draft: true
        files: |
          build/libs/GameBridge-0.1.1.jar
          build/libs/GameBridge-0.1.1-sources.jar
        body: |
          Test Message
          Test 2
        append_body: true


#    - name: Sleep command (no longer necessary)
#      run: sleep 30s
#      shell: bash
            
#    - name: Upload Jars as Artifacts
#      uses: actions/upload-artifact@v3
#      with:
#        name: Artifacts
#        path: build/libs
      
