# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Compiling and publishing

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set release tag
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Test release tag
      run: |
        echo $RELEASE_VERSION
        echo ${{ env.RELEASE_VERSION }}
    
#    - name: Set up JDK 17
#      uses: actions/setup-java@v3
#      with:
#        java-version: '17'
#        distribution: 'temurin'
#        
#    - name: Build Jar Files
#      uses: gradle/gradle-build-action@v2.11.1
#      with:
#        gradle-version: current
#        arguments: build
#        
#    - name: Upload Jars as Release Tag
#      uses: softprops/action-gh-release@v1
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      with:
#        name: 0.1.1
#        tag_name: 0.1.1
#        draft: true
#        files: |
#          build/libs/GameBridge-0.1.1.jar
#          build/libs/GameBridge-0.1.1-sources.jar
#        body: |
#          Test Message
#          Test 2
#        append_body: true
#
#
#    - name: Sleep command (no longer necessary)
#      run: sleep 30s
#      shell: bash
            
#    - name: Upload Jars as Artifacts
#      uses: actions/upload-artifact@v3
#      with:
#        name: Artifacts
#        path: build/libs
      
